#
# Table structure for table 'tt_content'
#
CREATE TABLE tt_content (
  `tx_impexp_origuid` int(11) NOT NULL DEFAULT 0,
  `tx_mask_slidenumbers` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_carouselinner` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_detailboxdesc` mediumtext DEFAULT NULL,
  `tx_mask_conatctbtn` mediumtext DEFAULT NULL,
  `tx_mask_contactbtnlink` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_orderbtn` mediumtext DEFAULT NULL,
  `tx_mask_orderbtnlink` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_detailboxtitle1` mediumtext DEFAULT NULL,
  `tx_mask_sliderheading1` mediumtext DEFAULT NULL,
  `tx_mask_abouttitle` mediumtext DEFAULT NULL,
  `tx_mask_aboutdesc` mediumtext DEFAULT NULL,
  `tx_mask_readbtnlink` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_readbtn` mediumtext DEFAULT NULL,
  `tx_mask_aboutimg` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_formlabel` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_socialbox` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_copyrighttxt` mediumtext DEFAULT NULL,
  `tx_mask_dishcontainer` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_foodheading` mediumtext DEFAULT NULL,
  `tx_mask_foodesc` mediumtext DEFAULT NULL,
  `tx_mask_readbtn1` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_hotheading` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_hotsubheading` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_carousel` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_appimg` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_percentage` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_apptxt` mediumtext DEFAULT NULL,
  `tx_mask_appdesc` mediumtext DEFAULT NULL,
  `tx_mask_appstoreimg` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_playstoreimg` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_form` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_content_parent_uid` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_content_role` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_content_tablenames` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_contactbox` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_socialhead` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_layoutclass` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_cnt_title` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_location_icon` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_location_info` mediumtext DEFAULT NULL,
  `tx_mask_call_icon` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_tele_link` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_mail_icon` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_mail_link` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_crsl_imgs` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_btn1_name` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_btn1_link` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_btn2_name` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_btn2_link` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_btn_name` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_btn_link` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_dish_imgs` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_fd_btn_name` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_fd_btn_link` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_desc` mediumtext DEFAULT NULL,
  `tx_mask_app_desc` mediumtext DEFAULT NULL,
  `tx_mask_hot_carousel` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_side_heading` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_client_heading` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_carousel_item` int(10) unsigned NOT NULL DEFAULT 0,
  KEY `tx_mask_content_parent_uid` (`tx_mask_content_parent_uid`)
);

DROP TABLE IF EXISTS `tx_mask_carousel`;
CREATE TABLE `tx_mask_carousel` (
  `uid` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `pid` int(10) unsigned NOT NULL DEFAULT 0,
  `tstamp` int(10) unsigned NOT NULL DEFAULT 0,
  `crdate` int(10) unsigned NOT NULL DEFAULT 0,
  `deleted` smallint(5) unsigned NOT NULL DEFAULT 0,
  `hidden` smallint(5) unsigned NOT NULL DEFAULT 0,
  `starttime` int(10) unsigned NOT NULL DEFAULT 0,
  `endtime` int(10) unsigned NOT NULL DEFAULT 0,
  `fe_group` varchar(255) NOT NULL DEFAULT '0',
  `sorting` int(11) NOT NULL DEFAULT 0,
  `editlock` smallint(5) unsigned NOT NULL DEFAULT 0,
  `sys_language_uid` int(11) NOT NULL DEFAULT 0,
  `l10n_parent` int(10) unsigned NOT NULL DEFAULT 0,
  `l10n_source` int(10) unsigned NOT NULL DEFAULT 0,
  `l10n_state` text DEFAULT NULL,
  `t3_origuid` int(10) unsigned NOT NULL DEFAULT 0,
  `l10n_diffsource` mediumblob DEFAULT NULL,
  `t3ver_oid` int(10) unsigned NOT NULL DEFAULT 0,
  `t3ver_wsid` int(10) unsigned NOT NULL DEFAULT 0,
  `t3ver_state` smallint(6) NOT NULL DEFAULT 0,
  `t3ver_stage` int(11) NOT NULL DEFAULT 0,
  `tx_mask_carouselimg` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_itemrate` mediumtext DEFAULT NULL,
  `tx_mask_itemdesc` mediumtext DEFAULT NULL,
  `tx_mask_orderbtnlink` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_orderbtn` mediumtext DEFAULT NULL,
  `parentid` int(11) NOT NULL DEFAULT 0,
  `parenttable` varchar(255) DEFAULT '',
   PRIMARY KEY (`uid`),
   KEY `parent` (`pid`,`deleted`,`hidden`),
   KEY `translation_source` (`l10n_source`),
   KEY `t3ver_oid` (`t3ver_oid`,`t3ver_wsid`)
);

DROP TABLE IF EXISTS `tx_mask_carouselinner`;
CREATE TABLE `tx_mask_carouselinner` (
    `uid` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `pid` int(10) unsigned NOT NULL DEFAULT 0,
  `tstamp` int(10) unsigned NOT NULL DEFAULT 0,
  `crdate` int(10) unsigned NOT NULL DEFAULT 0,
  `deleted` smallint(5) unsigned NOT NULL DEFAULT 0,
  `hidden` smallint(5) unsigned NOT NULL DEFAULT 0,
  `starttime` int(10) unsigned NOT NULL DEFAULT 0,
  `endtime` int(10) unsigned NOT NULL DEFAULT 0,
  `fe_group` varchar(255) NOT NULL DEFAULT '0',
  `sorting` int(11) NOT NULL DEFAULT 0,
  `editlock` smallint(5) unsigned NOT NULL DEFAULT 0,
  `sys_language_uid` int(11) NOT NULL DEFAULT 0,
  `l10n_parent` int(10) unsigned NOT NULL DEFAULT 0,
  `l10n_source` int(10) unsigned NOT NULL DEFAULT 0,
  `l10n_state` text DEFAULT NULL,
  `t3_origuid` int(10) unsigned NOT NULL DEFAULT 0,
  `l10n_diffsource` mediumblob DEFAULT NULL,
  `t3ver_oid` int(10) unsigned NOT NULL DEFAULT 0,
  `t3ver_wsid` int(10) unsigned NOT NULL DEFAULT 0,
  `t3ver_state` smallint(6) NOT NULL DEFAULT 0,
  `t3ver_stage` int(11) NOT NULL DEFAULT 0,
  `tx_mask_imgclass` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_img` int(10) unsigned NOT NULL DEFAULT 0,
  `parentid` int(11) NOT NULL DEFAULT 0,
  `parenttable` varchar(255) DEFAULT '',
   PRIMARY KEY (`uid`),
   KEY `parent` (`pid`,`deleted`,`hidden`),
   KEY `translation_source` (`l10n_source`),
   KEY `t3ver_oid` (`t3ver_oid`,`t3ver_wsid`)
);

DROP TABLE IF EXISTS `tx_mask_carousel_item`;
CREATE TABLE `tx_mask_carousel_item` (
    `uid` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `pid` int(10) UNSIGNED NOT NULL DEFAULT 0,
    `tstamp` int(10) UNSIGNED NOT NULL DEFAULT 0,
    `crdate` int(10) UNSIGNED NOT NULL DEFAULT 0,
    `deleted` smallint(5) UNSIGNED NOT NULL DEFAULT 0,
    `hidden` smallint(5) UNSIGNED NOT NULL DEFAULT 0,
    `starttime` int(10) UNSIGNED NOT NULL DEFAULT 0,
    `endtime` int(10) UNSIGNED NOT NULL DEFAULT 0,
    `fe_group` varchar(255) NOT NULL DEFAULT '0',
    `sorting` int(11) NOT NULL DEFAULT 0,
    `editlock` smallint(5) UNSIGNED NOT NULL DEFAULT 0,
    `sys_language_uid` int(11) NOT NULL DEFAULT 0,
    `l10n_parent` int(10) UNSIGNED NOT NULL DEFAULT 0,
    `l10n_source` int(10) UNSIGNED NOT NULL DEFAULT 0,
    `l10n_state` text DEFAULT NULL,
    `t3_origuid` int(10) UNSIGNED NOT NULL DEFAULT 0,
    `l10n_diffsource` mediumblob DEFAULT NULL,
    `t3ver_oid` int(10) UNSIGNED NOT NULL DEFAULT 0,
    `t3ver_wsid` int(10) UNSIGNED NOT NULL DEFAULT 0,
    `t3ver_state` smallint(6) NOT NULL DEFAULT 0,
    `t3ver_stage` int(11) NOT NULL DEFAULT 0,
    `tx_mask_client_img` int(10) unsigned NOT NULL DEFAULT 0,
    `tx_mask_client_name` varchar(255) NOT NULL DEFAULT '',
    `tx_mask_client_info` mediumtext DEFAULT NULL,
    `parentid` int(11) NOT NULL DEFAULT 0,
    `parenttable` varchar(255) DEFAULT '',
    PRIMARY KEY (`uid`),
    KEY `parent` (`pid`,`deleted`,`hidden`),
    KEY `translation_source` (`l10n_source`),
    KEY `t3ver_oid` (`t3ver_oid`,`t3ver_wsid`)
);

DROP TABLE IF EXISTS `tx_mask_contactbox`;
CREATE TABLE `tx_mask_contactbox` (
      `uid` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
      `pid` int(10) UNSIGNED NOT NULL DEFAULT 0,
      `tstamp` int(10) UNSIGNED NOT NULL DEFAULT 0,
      `crdate` int(10) UNSIGNED NOT NULL DEFAULT 0,
      `deleted` smallint(5) UNSIGNED NOT NULL DEFAULT 0,
      `hidden` smallint(5) UNSIGNED NOT NULL DEFAULT 0,
      `starttime` int(10) UNSIGNED NOT NULL DEFAULT 0,
      `endtime` int(10) UNSIGNED NOT NULL DEFAULT 0,
      `fe_group` varchar(255) NOT NULL DEFAULT '0',
      `sorting` int(11) NOT NULL DEFAULT 0,
      `editlock` smallint(5) UNSIGNED NOT NULL DEFAULT 0,
      `sys_language_uid` int(11) NOT NULL DEFAULT 0,
      `l10n_parent` int(10) UNSIGNED NOT NULL DEFAULT 0,
      `l10n_source` int(10) UNSIGNED NOT NULL DEFAULT 0,
      `l10n_state` text DEFAULT NULL,
      `t3_origuid` int(10) UNSIGNED NOT NULL DEFAULT 0,
      `l10n_diffsource` mediumblob DEFAULT NULL,
      `t3ver_oid` int(10) UNSIGNED NOT NULL DEFAULT 0,
      `t3ver_wsid` int(10) UNSIGNED NOT NULL DEFAULT 0,
      `t3ver_state` smallint(6) NOT NULL DEFAULT 0,
      `t3ver_stage` int(11) NOT NULL DEFAULT 0,
      `tx_mask_contactimg` int(10) UNSIGNED NOT NULL DEFAULT 0,
      `parentid` int(11) NOT NULL DEFAULT 0,
      `parenttable` varchar(255) DEFAULT '',
      PRIMARY KEY (`uid`),
      KEY `parent` (`pid`,`deleted`,`hidden`),
      KEY `translation_source` (`l10n_source`),
      KEY `t3ver_oid` (`t3ver_oid`,`t3ver_wsid`)
);

DROP TABLE IF EXISTS `tx_mask_dishcontainer`;
CREATE TABLE `tx_mask_dishcontainer` (
     `uid` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
     `pid` int(10) UNSIGNED NOT NULL DEFAULT 0,
     `tstamp` int(10) UNSIGNED NOT NULL DEFAULT 0,
     `crdate` int(10) UNSIGNED NOT NULL DEFAULT 0,
     `deleted` smallint(5) UNSIGNED NOT NULL DEFAULT 0,
     `hidden` smallint(5) UNSIGNED NOT NULL DEFAULT 0,
     `starttime` int(10) UNSIGNED NOT NULL DEFAULT 0,
     `endtime` int(10) UNSIGNED NOT NULL DEFAULT 0,
     `fe_group` varchar(255) NOT NULL DEFAULT '0',
     `sorting` int(11) NOT NULL DEFAULT 0,
     `editlock` smallint(5) UNSIGNED NOT NULL DEFAULT 0,
     `sys_language_uid` int(11) NOT NULL DEFAULT 0,
     `l10n_parent` int(10) UNSIGNED NOT NULL DEFAULT 0,
     `l10n_source` int(10) UNSIGNED NOT NULL DEFAULT 0,
     `l10n_state` text DEFAULT NULL,
     `t3_origuid` int(10) UNSIGNED NOT NULL DEFAULT 0,
     `l10n_diffsource` mediumblob DEFAULT NULL,
     `t3ver_oid` int(10) UNSIGNED NOT NULL DEFAULT 0,
     `t3ver_wsid` int(10) UNSIGNED NOT NULL DEFAULT 0,
     `t3ver_state` smallint(6) NOT NULL DEFAULT 0,
     `t3ver_stage` int(11) NOT NULL DEFAULT 0,
     `tx_mask_dishimg` int(10) UNSIGNED NOT NULL DEFAULT 0,
     `parentid` int(11) NOT NULL DEFAULT 0,
     `parenttable` varchar(255) DEFAULT '',
     PRIMARY KEY (`uid`),
     KEY `parent` (`pid`,`deleted`,`hidden`),
     KEY `translation_source` (`l10n_source`),
     KEY `t3ver_oid` (`t3ver_oid`,`t3ver_wsid`)
);

DROP TABLE IF EXISTS `tx_mask_slidenumbers`;
CREATE TABLE `tx_mask_slidenumbers` (
    `uid` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `pid` int(10) UNSIGNED NOT NULL DEFAULT 0,
    `tstamp` int(10) UNSIGNED NOT NULL DEFAULT 0,
    `crdate` int(10) UNSIGNED NOT NULL DEFAULT 0,
    `deleted` smallint(5) UNSIGNED NOT NULL DEFAULT 0,
    `hidden` smallint(5) UNSIGNED NOT NULL DEFAULT 0,
    `starttime` int(10) UNSIGNED NOT NULL DEFAULT 0,
    `endtime` int(10) UNSIGNED NOT NULL DEFAULT 0,
    `fe_group` varchar(255) NOT NULL DEFAULT '0',
    `sorting` int(11) NOT NULL DEFAULT 0,
    `editlock` smallint(5) UNSIGNED NOT NULL DEFAULT 0,
    `sys_language_uid` int(11) NOT NULL DEFAULT 0,
    `l10n_parent` int(10) UNSIGNED NOT NULL DEFAULT 0,
    `l10n_source` int(10) UNSIGNED NOT NULL DEFAULT 0,
    `l10n_state` text DEFAULT NULL,
    `t3_origuid` int(10) UNSIGNED NOT NULL DEFAULT 0,
    `l10n_diffsource` mediumblob DEFAULT NULL,
    `t3ver_oid` int(10) UNSIGNED NOT NULL DEFAULT 0,
    `t3ver_wsid` int(10) UNSIGNED NOT NULL DEFAULT 0,
    `t3ver_state` smallint(6) NOT NULL DEFAULT 0,
    `t3ver_stage` int(11) NOT NULL DEFAULT 0,
    `tx_mask_dataslideto` varchar(255) NOT NULL DEFAULT '',
    `tx_mask_number` int(11) NOT NULL DEFAULT 0,
    `parentid` int(11) NOT NULL DEFAULT 0,
    `parenttable` varchar(255) DEFAULT '',
    PRIMARY KEY (`uid`),
    KEY `parent` (`pid`,`deleted`,`hidden`),
    KEY `translation_source` (`l10n_source`),
    KEY `t3ver_oid` (`t3ver_oid`,`t3ver_wsid`)
);

DROP TABLE IF EXISTS `tx_mask_socialbox`;
CREATE TABLE `tx_mask_socialbox` (
     `uid` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
     `pid` int(10) UNSIGNED NOT NULL DEFAULT 0,
     `tstamp` int(10) UNSIGNED NOT NULL DEFAULT 0,
     `crdate` int(10) UNSIGNED NOT NULL DEFAULT 0,
     `deleted` smallint(5) UNSIGNED NOT NULL DEFAULT 0,
     `hidden` smallint(5) UNSIGNED NOT NULL DEFAULT 0,
     `starttime` int(10) UNSIGNED NOT NULL DEFAULT 0,
     `endtime` int(10) UNSIGNED NOT NULL DEFAULT 0,
     `fe_group` varchar(255) NOT NULL DEFAULT '0',
     `sorting` int(11) NOT NULL DEFAULT 0,
     `editlock` smallint(5) UNSIGNED NOT NULL DEFAULT 0,
     `sys_language_uid` int(11) NOT NULL DEFAULT 0,
     `l10n_parent` int(10) UNSIGNED NOT NULL DEFAULT 0,
     `l10n_source` int(10) UNSIGNED NOT NULL DEFAULT 0,
     `l10n_state` text DEFAULT NULL,
     `t3_origuid` int(10) UNSIGNED NOT NULL DEFAULT 0,
     `l10n_diffsource` mediumblob DEFAULT NULL,
     `t3ver_oid` int(10) UNSIGNED NOT NULL DEFAULT 0,
     `t3ver_wsid` int(10) UNSIGNED NOT NULL DEFAULT 0,
     `t3ver_state` smallint(6) NOT NULL DEFAULT 0,
     `t3ver_stage` int(11) NOT NULL DEFAULT 0,
     `tx_mask_sociallink` varchar(255) NOT NULL DEFAULT '',
     `tx_mask_socialimg` int(10) UNSIGNED NOT NULL DEFAULT 0,
     `parentid` int(11) NOT NULL DEFAULT 0,
     `parenttable` varchar(255) DEFAULT '',
     PRIMARY KEY (`uid`),
     KEY `parent` (`pid`,`deleted`,`hidden`),
     KEY `translation_source` (`l10n_source`),
     KEY `t3ver_oid` (`t3ver_oid`,`t3ver_wsid`)
);

DROP TABLE IF EXISTS `tx_mask_hot_carousel`;
CREATE TABLE `tx_mask_hot_carousel` (
  `uid` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `pid` int(10) unsigned NOT NULL DEFAULT 0,
  `tstamp` int(10) unsigned NOT NULL DEFAULT 0,
  `crdate` int(10) unsigned NOT NULL DEFAULT 0,
  `deleted` smallint(5) unsigned NOT NULL DEFAULT 0,
  `hidden` smallint(5) unsigned NOT NULL DEFAULT 0,
  `starttime` int(10) unsigned NOT NULL DEFAULT 0,
  `endtime` int(10) unsigned NOT NULL DEFAULT 0,
  `fe_group` varchar(255) NOT NULL DEFAULT '0',
  `sorting` int(11) NOT NULL DEFAULT 0,
  `editlock` smallint(5) unsigned NOT NULL DEFAULT 0,
  `sys_language_uid` int(11) NOT NULL DEFAULT 0,
  `l10n_parent` int(10) unsigned NOT NULL DEFAULT 0,
  `l10n_source` int(10) unsigned NOT NULL DEFAULT 0,
  `l10n_state` text DEFAULT NULL,
  `t3_origuid` int(10) unsigned NOT NULL DEFAULT 0,
  `l10n_diffsource` mediumblob DEFAULT NULL,
  `t3ver_oid` int(10) unsigned NOT NULL DEFAULT 0,
  `t3ver_wsid` int(10) unsigned NOT NULL DEFAULT 0,
  `t3ver_state` smallint(6) NOT NULL DEFAULT 0,
  `t3ver_stage` int(11) NOT NULL DEFAULT 0,
  `tx_mask_item_img` int(10) unsigned NOT NULL DEFAULT 0,
  `tx_mask_crsl_desc` mediumtext DEFAULT NULL,
  `tx_mask_orderbtn` varchar(255) NOT NULL DEFAULT '',
  `tx_mask_orderbtnlink` varchar(255) NOT NULL DEFAULT '',
  `parentid` int(11) NOT NULL DEFAULT 0,
  `parenttable` varchar(255) DEFAULT '',
   PRIMARY KEY (`uid`),
   KEY `parent` (`pid`,`deleted`,`hidden`),
   KEY `translation_source` (`l10n_source`),
   KEY `t3ver_oid` (`t3ver_oid`,`t3ver_wsid`)
);